# Generated by Django 4.2 on 2024-11-14 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribers', models.CharField(max_length=100)),
                ('views', models.CharField(max_length=100)),
                ('engagment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='creatordetail',
            name='perks',
            field=models.ManyToManyField(blank=True, default=None, related_name='attributes', to='app.perk'),
        ),
        migrations.AddField(
            model_name='creatordetail',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stat'),
        ),
    ]
