# Generated by Django 4.2 on 2024-11-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stat_alter_creatordetail_perks_creatordetail_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stat',
            name='engagment',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stat',
            name='subscribers',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stat',
            name='views',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
