# Generated by Django 4.2 on 2024-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_stat_engagment_alter_stat_subscribers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
