# Generated by Django 4.2 on 2024-11-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatordetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='creatordetail',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stat'),
        ),
        migrations.AlterField(
            model_name='creatordetail',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
