# Generated by Django 4.2 on 2024-11-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_creatordetail_image_alter_creatordetail_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatordetail',
            name='creator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creatordetail',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='creatordetail',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='creatordetail',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creatordetail',
            name='tiktok_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='creatordetail',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='creatordetail',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
