# Generated by Django 4.2 on 2024-11-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_creatordetail_creator_creatordetail_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('review', models.TextField()),
                ('ratings', models.CharField(choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')], max_length=100)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
    ]
