# Generated by Django 4.2 on 2024-11-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_engagment_stat_engagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='ratings',
            field=models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')]),
        ),
    ]
