# Generated by Django 4.2 on 2024-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_activity_options_activity_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Activity Categories'},
        ),
        migrations.AddField(
            model_name='activity',
            name='energy_level',
            field=models.IntegerField(blank=True, help_text='0 for very relaxing, 100 for very energetic', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='stress_level',
            field=models.IntegerField(blank=True, help_text='0 for very relaxing, 100 for high intensity', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
